fixes v1.2.0
MaharaProject/mahara-mobile-cordova pull request #13
Opened 2017-01-18 21:26 UTC by alexey0511

2017-02-07 04:09 UTC, jenofdoom reviewed
A few comments

2017-02-07 04:09 UTC, jenofdoom commented on src/js/components/login/login.js
> +            this.nextButton();
Does this need to be bound in the class setup?

2017-02-07 04:09 UTC, jenofdoom commented on src/js/components/pending/pending.js
> +import {PENDING, PAGE_URL}           from '../../constants.js';
would be good to line up the whitespace on this

2017-02-07 04:09 UTC, jenofdoom commented on src/js/components/user/user.js
> +        icon += `?${Date.now() || ''}`;
is there anything else we can use that isn't so specific? this means the image will never be cached - if the version string is available that could be better?

2017-02-07 22:38 UTC, jenofdoom reviewed
Commit name for the last commit isn't great, if it is just part of the prev commit then do an amend commit and force push

2017-02-07 23:47 UTC, alexey0511 commented on src/js/components/user/user.js
> +        icon += `?${Date.now() || ''}`;
This is user specific information. I'm affraid the only what we can rely on is a timestamp

2017-02-07 23:47 UTC, alexey0511 commented on src/js/components/pending/pending.js
> +import {PENDING, PAGE_URL}           from '../../constants.js';
done

2017-02-07 23:47 UTC, alexey0511 commented on src/js/components/user/user.js
> +        icon += `?${Date.now() || ''}`;
It's user specific info. I'm afraid the most reliable thing would be the timestamp

2017-02-07 23:47 UTC, alexey0511 commented on src/js/components/login/login.js
> +            this.nextButton();
What would be better way to do it? ( it hasn't been implemented using form )

2017-02-09 02:10 UTC, agwells requested changes

2017-02-09 02:10 UTC, agwells commented on src/js/components/user/user.js
> +        icon += `?${Date.now() || ''}`;
I agree with Jen, the render() method isn't the best place to do this. It means that every time the component re-renders, the image will refresh. It also prevents this component from being "pure" (always producing the same output given the same input), which can hurt React performance.

The user profile icon is actually downloaded into local storage, and the URL we're using here points to the file in local storage. This happens in the "refreshUserIcon" method, in get-sync-data.js. So, you could add a timestamp to the URL generated there, on line 118 of that file.

2017-02-09 02:10 UTC, agwells commented on src/js/components/login/login.js
> +            this.nextButton();
I think the correct way to do it, would be to surround this with a &lt;form> tag, and make its onsubmit function be this.nextButton.

https://facebook.github.io/react/docs/forms.html

2017-02-09 02:10 UTC, agwells commented on src/js/components/server/server.js
> +  handleUrlSubmit = (e) => {
Same here as in login.js. We should use a &lt;form> tag, with an onsubmit.

2017-02-09 22:40 UTC, merged